export const cardList = [
    {
        id: 1,
        theme: 'Web Design',
        title: 'Название задачи',
        date: '30.10.23',
        status: 'Без статуса',
    },
    {
        id: 2,
        theme: 'Research',
        title: 'Задача по исследованию',
        date: '25.09.23',
        status: 'Нужно сделать',
    },
    {
        id: 3,
        theme: 'Research',
        title: 'Проект дизайна интерфейса',
        date: '20.08.23',
        status: 'Без статуса',
    },
    {
        id: 4,
        theme: 'Web Design',
        title: 'Дизайн макета сайта',
        date: '15.07.23',
        status: 'Без статуса',
    },
    {
        id: 5,
        theme: 'Copywriting',
        title: 'Создание React компонента',
        date: '10.06.23',
        status: 'Без статуса',
    },
    {
        id: 6,
        theme: 'Research',
        title: 'Проект дизайна интерфейса',
        date: '20.08.23',
        status: 'Без статуса',
    },
    {
        id: 7,
        theme: 'Research',
        title: 'Проект дизайна интерфейса',
        date: '20.08.23',
        status: 'В работе',
    },
    {
        id: 8,
        theme: 'Copywriting',
        title: 'Создание React компонента',
        date: '10.06.23',
        status: 'В работе',
    },
    {
        id: 9,
        theme: 'Web Design',
        title: 'Дизайн макета сайта',
        date: '15.07.23',
        status: 'В работе',
    },
    {
        id: 10,
        theme: 'Research',
        title: 'Создание React компонента',
        date: '10.06.23',
        status: 'Тестирование',
    },
    {
        id: 11,
        theme: 'Research',
        title: 'Название задачи',
        date: '15.07.23',
        status: 'Готово',
    }

]